from enum import Enum


class Route(Enum):
    INDEX = "/"
    LOGIN = "/login"
    RECUPERAR_CONTRASEÑA = "/login/recuperar_password"
    FACULTATIVO = "/facultativo"
    PACIENTE = "/paciente"
    GESTION_FACULTATIVOS = "/facultativo/gestion_facultativos"
    ESTADOS_PACIENTES = "/facultativo/estados_paciente"
    GESTION_PACIENTES = "/facultativo/gestion_pacientes"
    CONSTRUCCION = "/construccion"
    PROYECTO_BEHUMANEST = "/en_consulta/proyecto_behumanest"
    INDICACIONES_GENERALES = "/indicaciones_preoperatorias/indicaciones_generales"
    COMUNICACION_INGRESO = "/ingreso/comunicacion_fecha_ingreso"
    UBICACION_ESPERA = "/informacion_familias/ubicaciones_de_espera"
    CONSENTIMIENTOS = "/en_consulta/consentimientos"
    QUE_VAMOS_A_HACER = "/en_consulta/que_vamos_a_hacer"
    COMUNICACION_BEHUMANEST = "/informacion_familias/comunicacion_behumanest"
    TRASLADO_QUIROFANO = "/dia_intervencion/traslado_quirofano"
    TELEFONOS_INTERES = "/telefonos_interes"
    EN_PLANTA = "/dia_intervencion/en_planta"
    UBICACION_CONSULTA="/en_consulta/ubicacion"
    UBICACION_ACCESO_INGRESO="/ingreso/ubicacion_acceso"
    QUE_LLEVAR_INGRESO="/ingreso/que_debo_llevar"
    PREPARACION_PREVIA="/ingreso/preparacion_previa"
    POLITICA_PRIVACIDAD="/politica_privacidad"
    AVISO_LEGAL="/aviso_legal"